{
 "title": " pfSense Firewall Monitoring",
 "tags": [
  "snmp",
  "security",
  "firewall"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(pfStatusRunning,job)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(ifAdminStatus{job=\"$job\"},ifName)"
    }
   },
   {
    "name": "pfLabel",
    "label": "PF Label",
    "query": {
     "query": "label_values(pfLabelsLblEvals{job=\"$job\"},pfLabelsLblName)"
    }
   },
   {
    "name": "interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "timeticks" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "pfStatusRuntime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Filter by Interface",
   "type": "table",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "max(pfInterfacesIfRefsRule{job=\"$job\",pfInterfacesIfDescr=~\"$interface\"}) by (pfInterfacesIfIndex, pfInterfacesIfDescr)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(pfInterfacesIf4BytesInBlock{job=\"$job\",pfInterfacesIfDescr=~\"$interface\"} + pfInterfacesIf6BytesInBlock{job=\"$job\",pfInterfacesIfDescr=~\"$interface\"}) by (pfInterfacesIfIndex)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(pfInterfacesIf4BytesOutBlock{job=\"$job\",pfInterfacesIfDescr=~\"$interface\"} + pfInterfacesIf6BytesInBlock{job=\"$job\",pfInterfacesIfDescr=~\"$interface\"}) by (pfInterfacesIfIndex)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(pfInterfacesIfTZero{job=\"$job\",pfInterfacesIfDescr=~\"$interface\"}) by (pfInterfacesIfIndex)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(pfInterfacesIf4BytesInPass{job=\"$job\",pfInterfacesIfDescr=~\"$interface\"} + pfInterfacesIf6BytesInPass{job=\"$job\",pfInterfacesIfDescr=~\"$interface\"}) by (pfInterfacesIfIndex)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(pfInterfacesIf4BytesOutPass{job=\"$job\",pfInterfacesIfDescr=~\"$interface\"} + pfInterfacesIf6BytesOutPass{job=\"$job\",pfInterfacesIfDescr=~\"$interface\"}) by (pfInterfacesIfIndex)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load 5",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laLoadInt{job=\"$job\", laNames=\"Load-5\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ssCpuIdle{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load 15",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "laLoadInt{job=\"$job\", laNames=\"Load-15\"} / 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Filter by Lable",
   "type": "table",
   "gridPos": { "h": 15, "w": 18, "x": 6, "y": 6 },
   "targets": [
    {
     "expr": "max(pfLabelsLblEvals{job=\"$job\",pfLabelsLblName=~\"$pfLabel\"}) by (pfLabelsLblIndex)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(pfLabelsLblBytesIn{job=\"$job\",pfLabelsLblName=~\"$pfLabel\"}) by (pfLabelsLblIndex, pfLabelsLblName)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(pfLabelsLblBytesOut{job=\"$job\",pfLabelsLblName=~\"$pfLabel\"}) by (pfLabelsLblIndex)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memAvailReal{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - ((memAvailReal{job=\"$job\"} / memTotalReal{job=\"$job\"}) * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memTotalReal{job=\"$job\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dskTotal", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "stat",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(dskUsedLow{job=\"$job\"}) / sum(dskTotalLow{job=\"$job\"})) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Used",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dskUsed", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Interface State",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "max(ifAdminStatus{job=\"$job\", ifName=~\"$interface\"}) by (ifIndex, ifName, ifAlias)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(ifSpeed{job=\"$job\", ifName=~\"$interface\"}) by (ifIndex)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(ifInErrors{job=\"$job\", ifName=~\"$interface\"}) by (ifIndex)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(ifOutErrors{job=\"$job\", ifName=~\"$interface\"}) by (ifIndex)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(ifInDiscards{job=\"$job\", ifName=~\"$interface\"}) by (ifIndex)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(ifOutDiscards{job=\"$job\", ifName=~\"$interface\"}) by (ifIndex)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{job=\"$job\", ifName=~\"$interface\"}[$interval]) * 8",
     "legendFormat": "In: {{ ifName }} ({{ ifAlias }})"
    },
    {
     "expr": "- irate(ifHCOutOctets{job=\"pfsense\", ifName=~\"$interface\"}[$interval]) * 8",
     "legendFormat": "Out: {{ ifName }} ({{ ifAlias }})"
    }
   ]
  }
 ]
}