groups:
- name: interface-alert.rules
  rules:
  - alert: InterfaceDown
    expr: ifOperStatus{ifDescr!~"^(lo|pf.*|pflog.*|veth.*|docker.*)"} == 2 
    for: 1m
    labels:
      severity: critical
      alert_type: interface_status 
    annotations:
      summary: "Interface DOWN: {{ $labels.ifDescr }}"
      description: "Interface {{ $labels.ifDescr }} on {{ $labels.instance }} is DOWN" 
