# Backup alert rule
groups:
- name: backup-status
  rules:
  - alert: BackupFailed
    expr: auto_backup_status{job="prometheus"} == 1
    for: 5m
    labels:
      severity: 'critical'
    annotations:
      summary: "Backup FAILED on {{ $labels.host }} ({{ $labels.system }})"
      description: |-
        Automatic backup failed!
        Host: {{ $labels.host }}
        System: {{ $labels.system }}
        Last update: {{ $labels.timestamp }} 
