groups:
- name: backup-status
  rules:
  - alert: BackupFailed
    expr: auto_backup_status{job="teleport-server"} == 1
    for: 5m
    labels:
      severity: critical
      alert_type: backup 
    annotations:
      summary: "Backup FAILED on {{ $labels.host }}"
      description: "{{ $labels.error }}"
      last_run: "{{ $labels.timestamp }}" 
