groups:
- name: pfsense.rules
  rules:
  - record: pfsense:memory:usage_percent
    expr: 100 - ((memAvailReal / memTotalReal) * 100)

- name: memory-usage-alerts
  rules:
  - alert: MemoryUsageNotice
    expr: pfsense:memory:usage_percent > 60 and pfsense:memory:usage_percent <= 70
    for: 10m
    labels:
      severity: notice
      alert_type: memory
    annotations:
      summary: "Memory Usage Notice"
      description: "Memory usage is {{ $value | printf \"%.2f\" }}%"
      value: "{{ $value | printf \"%.2f\" }}" 

  - alert: MemoryUsageWarning
    expr: pfsense:memory:usage_percent > 70 and pfsense:memory:usage_percent <= 80
    for: 5m
    labels:
      severity: warning
      alert_type: memory
    annotations:
      summary: "Memory Usage Warning"
      description: "Memory usage is {{ $value | printf \"%.2f\" }}%"
      value: "{{ $value | printf \"%.2f\" }}"

  - alert: MemoryUsageCritical
    expr: pfsense:memory:usage_percent > 80 and pfsense:memory:usage_percent <= 90
    for: 3m
    labels:
      severity: critical
      alert_type: memory
    annotations:
      summary: "Memory Usage Critical"
      description: "Memory usage is {{ $value | printf \"%.2f\" }}%"
      value: "{{ $value | printf \"%.2f\" }}"

  - alert: MemoryUsageEmergency
    expr: pfsense:memory:usage_percent > 90
    for: 1m
    labels:
      severity: emergency
      alert_type: memory
    annotations:
      summary: "Memory Usage EMERGENCY"
      description: "Memory usage is {{ $value | printf \"%.2f\" }}%"
      value: "{{ $value | printf \"%.2f\" }}"
