---
- name: Remove Nginx
  hosts: "{{ target_hosts }}"
  become: yes

  tasks:
    - name: Stop Nginx service
      systemd:
        name: nginx
        state: stopped
      ignore_errors: yes

    - name: Disable Nginx service
      systemd:
        name: nginx
        enabled: no
      ignore_errors: yes

    - name: Remove Nginx package
      apt:
        name: nginx
        state: absent
        purge: yes
        autoremove: yes

    - name: Remove Nginx config directories
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /etc/nginx
        - /var/www/html
        - /var/log/nginx
      ignore_errors: yes

    - name: Remove Nginx log files
      shell: rm -rf /var/log/nginx*
      ignore_errors: yes

- import_playbook: nginx-exporter-remove.yaml
