global:
  resolve_timeout: 5m

route:
  group_by: ['alertname', 'severity', 'alert_type']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'telegram-alerts' 
  
  routes:
  # --- NO  RESOLVE (CPU, Disk, Memory, Network, Security, Backup) ---
  - match:
      alert_type: memory
    receiver: 'telegram-alerts-no-resolve'
    group_by: [alertname, instance, severity]
    continue: false

  - match:
      alert_type: 'network_traffic'
    receiver: 'telegram-alerts-no-resolve'
    group_by: [alertname, ifName, severity]
    continue: false

  - match:
      alert_type: 'network_anomaly'
    receiver: 'telegram-alerts-no-resolve'
    group_by: [alertname, instance]
    continue: false

  - match:
      alert_type: disk
    receiver: 'telegram-alerts-no-resolve'
    group_by: [alertname, instance, mountpoint]
    continue: false

  - match:
      alert_type: cpu
    receiver: 'telegram-alerts-no-resolve'
    group_by: [alertname, instance]
    continue: false

  - match:
      alert_type: security
    receiver: 'telegram-alerts-no-resolve'
    group_by: [alertname, src_ip, msg] 
    continue: false
    
  - match:
      alert_type: backup
    receiver: 'telegram-alerts-no-resolve'
    group_by: [alertname, host, system]
    continue: false

  # --- RESOLVE (Availability, Interface) ---
  - match:
      alert_type: availability
    receiver: 'telegram-alerts'
    group_by: [alertname, instance]
    continue: false

  - match:
      alert_type: 'interface_status'
    receiver: 'telegram-alerts'
    group_by: [alertname, instance, ifDescr]
    continue: false

receivers:
- name: 'telegram-alerts'
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 7926001781:AAGyByulcRakN7riHRdw1AOwGazYztXpeaI
    chat_id: -4638379865    
    message: '{{ template "telegram.main" . }}' 
    parse_mode: 'HTML'
    send_resolved: true

- name: 'telegram-alerts-no-resolve'
  telegram_configs:
  - api_url: https://api.telegram.org
    bot_token: 7926001781:AAGyByulcRakN7riHRdw1AOwGazYztXpeaI
    chat_id: -4638379865    
    message: '{{ template "telegram.main" . }}' 
    parse_mode: 'HTML'
    send_resolved: false  

- name: 'auto-block-webhook'
  webhook_configs:
  - url: 'http://192.168.254.100:9000/hooks/block-ip'
    send_resolved: false

templates:
- /etc/alertmanager/templates/*.tmpl
